// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC17FMmKWC8yf2bKPMrsDrRiev5VvIhB-A',
    appId: '1:911589781893:web:efa225fb7952768bd654ec',
    messagingSenderId: '911589781893',
    projectId: 'car-wash-app-d4cfd',
    authDomain: 'car-wash-app-d4cfd.firebaseapp.com',
    storageBucket: 'car-wash-app-d4cfd.firebasestorage.app',
    measurementId: 'G-MSEQ10820S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClCha0UCHOveuSvvBlGXaAhsLetECotgw',
    appId: '1:911589781893:android:def8ff69b953c640d654ec',
    messagingSenderId: '911589781893',
    projectId: 'car-wash-app-d4cfd',
    storageBucket: 'car-wash-app-d4cfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Di5m4riiZ1wLovJ77htm8QDLnC4mR4A',
    appId: '1:911589781893:ios:0ef35327c923f141d654ec',
    messagingSenderId: '911589781893',
    projectId: 'car-wash-app-d4cfd',
    storageBucket: 'car-wash-app-d4cfd.firebasestorage.app',
    iosBundleId: 'com.example.carWashApp',
  );
}
